name: frontend_aps
description: "A new Flutter project."
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.19.0 
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  freezed_annotation: ^2.4.1
  provider: ^6.0.5
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  liquid_pull_to_refresh: ^3.0.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.6
  flutter_lints: ^2.0.0
 
flutter:
 
  uses-material-design: true 
  assets:
    - assets/images/
    - assets/icons/